### ISSUE TITLE
[Feat]: 希望增加列表下拉刷新功能

### ISSUE THREAD

**Issue by BigPigHoof** [digitalchina-frontend/matrix-wechat-app#17]
### 问题描述

景区列表是通过下拉加载的，但是无法刷新整个列表，增加一个下拉刷新，方便用户看到最新数据

### 解决方案

待补充

**Comment by fancn21th** [comment]
@BigPigHoof  有没有参考解决方案

**Comment by BigPigHoof** [comment]
> @BigPigHoof 有没有参考解决方案

官方组件“scroll-view”有下拉刷新功能，代码我已经加上，等下提交个pr
