### ISSUE TITLE
main 分支瘦身

### ISSUE THREAD

**Issue by fancn21th** [digitalchina-frontend/matrix-wechat-app#4]
去掉 main 分支不必要的代码 保留一个页面 作为 写 demo 的极简模版

**Comment by fancn21th** [comment]
参考 代码片段的 文件结构

```shell
├── app.js
├── app.json
├── app.wxss
├── index
│   ├── index.js
│   ├── index.wxml
│   └── index.wxss
├── project.config.json
└── project.private.config.json
```

**Comment by zlxiao97** [comment]
已参考微信小程序代码片段进行调整，多出的文件有：

- README.md：项目说明文档
- changelog.config.js：git-cz 配置文件
- package.json：npm 包配置文件
- pnpm-lock.yaml：pnpm 依赖包描述文件

除了多出上述文件外，额外创建了 `/pages/` 目录用于存放页面文件夹，除此之外的目录结构与小程序代码片段的文件结构一致，其含义可以参考[目录结构 | 微信开放文档](https://developers.weixin.qq.com/miniprogram/dev/framework/structure.html)，完整的目录结构如下：

```
├── README.md
├── app.js
├── app.json
├── app.wxss
├── changelog.config.js
├── package.json
├── pages
│   └── index
│       ├── index.js
│       ├── index.json
│       ├── index.wxml
│       └── index.wxss
├── pnpm-lock.yaml
├── project.config.json
└── sitemap.json
```

**Comment by zlxiao97** [comment]
目前根目录下文件较多，从便于维护的角度考虑可以创建 `/src/` 或 `/miniprogram/` 目录存放小程序相关文件，有任何建议吗？
@fancn21th

**Comment by fancn21th** [comment]
文件夹结构是属于架构层面设计， 今天会议上我们提到了 针对同一种案例 我们分别提供 基础版本 和 最佳实践版本。

最佳实践版本的设计 我还没有考虑清楚 倒不是因为对 微信小程序不熟悉的原因。 毕竟 技术可以认为是细节，架构上的考虑主要是围绕 业务。

前端本身是 整个应用的软件架构的末端， 是依赖链条的 底部， 但是在 前端领域内 又可以认为分为 更微观的 子领域。 领域的划分决定了架构设计的主题思想。 

这几天看 DDD 还需要琢磨一下。

**Comment by fancn21th** [comment]
any update @zlxiao97

**Comment by zlxiao97** [comment]
已将小程序相关文件（除项目配置文件）放入 `/miniprogram/` 并于 `project.config.json` 中配置 `miniprogramRoot`，配置参考[项目配置文件](https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html)。
目录结构如下：
```
├── README.md
├── changelog.config.js
├── miniprogram
│   ├── app.js
│   ├── app.json
│   ├── app.wxss
│   ├── pages
│   │   └── index
│   │       ├── index.js
│   │       ├── index.json
│   │       ├── index.wxml
│   │       └── index.wxss
│   └── sitemap.json
├── package.json
├── pnpm-lock.yaml
└── project.config.json
```
