### ISSUE TITLE
更容易理解、填写的 isssue 模板

### ISSUE THREAD

**Issue by zlxiao97** [digitalchina-frontend/matrix-wechat-app#8]
**Is your feature request related to a problem? Please describe.**
issue 模板是英文的，并且不便于填写。

**Describe the solution you'd like**
翻译中文 issue 模板，并且使用 [议题表单](https://docs.github.com/zh/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) 的交互方式方便贡献者填写 issue。

解决方案：
 在 `.github/ISSUE_TEMPLATE` 目录下创建 `.yml` 文件，分别对 Feature Request 和 Bug Report 类型表单进行配置，语法参考[议题表单的语法](https://docs.github.com/zh/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#%E9%A1%B6%E7%BA%A7%E8%AF%AD%E6%B3%95)以及[GitHub 表单架构的语法](https://docs.github.com/zh/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)。

**Describe alternatives you've considered**
暂无

**Additional context**
Feature Request 议题表单效果图：
![image](https://user-images.githubusercontent.com/43952326/216254328-944ecbf5-c41b-4d87-9193-7d8c624353bd.png)
Bug Report 议题表单效果图：
![image](https://user-images.githubusercontent.com/43952326/216254455-1b776ecf-ded1-4b66-860b-e822bcb65531.png)

**Comment by fancn21th** [comment]
妙手生花
